name: Deploy on Prod Env
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH Keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.PROD_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PROD_SSH_HOST }} > ~/.ssh/known_hosts
          
      - name: Connect, Pull and Deploy
        run: ssh ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} "export NVM_DIR=~/.nvm && source ~/.nvm/nvm.sh && cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.PROD_BRANCH }} && git pull && npm i --legacy-peer-deps && npm run build && pm2 reload web && exit"
      - name: cleanup
        run: rm -rf ~/.ssh